version: '3'
services:
  node-server:
    container_name: node-server
    build:
      context: ./server
      dockerfile: Dockerfile
    image: timetable/node-server
    restart: unless-stopped
    tty: true
    ports:
      - "8888:8888"
    environment: 
      - REDIS_ENDPOINT=redis

  # Redis
  redis:
    container_name: redis
    build:
      context: ./redis
      dockerfile: Dockerfile
    image: timetable/redis
    restart: unless-stopped
    tty: true
    # Port forwarding could be removed.
    # Would still be able to connect between containers, but not from host.
    ports: 
      - "127.0.0.1:6379:6379"
    volumes:
      - "./redis/data:/data"

  # Nginx Service
  # webserver:
  #   image: nginx:alpine
  #   container_name: webserver
  #   restart: unless-stopped
  #   tty: true
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./:/var/www/
  #     - ./nginx/conf.d/:/etc/nginx/conf.d/
  #     - ./nginx/ssl/:/etc/nginx/ssl/
  #   networks:
  #     - app-network
