version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: izar/php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/
    #volumes:
    #  - ./:/var/www/
    networks:
      - app-network

  # Redis
  redis:
    build:
      context: 
    container_name: redis
    restart: unless-stopped
    tty: true

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/ssl/:/etc/nginx/ssl/
    networks:
      - app-network

# Docker Networks
networks:
  app-network:
    driver: bridge
